CREATE TABLE users ( username VARCHAR(20) PRIMARY KEY ON CONFLICT FAIL NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL, password VARCHAR(80) NOT NULL ON CONFLICT FAIL, salt VARCHAR(5) NOT NULL ON CONFLICT FAIL ) WITHOUT ROWID;

CREATE TABLE tokens ( user VARCHAR(20) NOT NULL ON CONFLICT FAIL, token VARCHAR(25) PRIMARY KEY ON CONFLICT FAIL NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL, expire DATETIME NOT NULL ON CONFLICT FAIL, useragent TEXT NOT NULL ON CONFLICT FAIL, FOREIGN KEY ( user ) REFERENCES users ( username ) ON DELETE CASCADE ON UPDATE CASCADE ) WITHOUT ROWID;
